const Menu = [
    {
        id: 1,
        image: "images/aloo-pakora.jpg",
        name: "Allu Pakoda",
        category: "Evening",
        price: "20Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 2,
        image: "images/chole-bhature.jpg",
        name: "Chole Bhature",
        category: "Breakfast",
        price: "30Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 3,
        image: "images/corns.jpg",
        name: "Corns",
        category: "Evening",
        price: "25Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 4,
        image: "images/maggi.jpg",
        name: "Maggi",
        category: "Breakfast",
        price: "35Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 5,
        image: "images/momos.jpg",
        name: "Momos",
        category: "Evening",
        price: "40Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 6,
        image: "images/nonvegthali.jpg",
        name: "Non-Veg Thali",
        category: "Lunch",
        price: "70Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 7,
        image: "images/pav-bhaji.jpg",
        name: "Pav Bhaji",
        category: "Lunch",
        price: "50Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 8,
        image: "images/pizza.jpg",
        name: "Pizza",
        category: "Evening",
        price: "90Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 9,
        image: "images/poori.jpg",
        name: "Poori",
        category: "Dinner",
        price: "45Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 10,
        image: "images/rajmachawal.jpg",
        name: "Rajma Chawal",
        category: "Dinner",
        price: "60Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 11,
        image: "images/samosa.jpg",
        name: "Samosa",
        category: "Breakfast",
        price: "15Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 12,
        image: "images/sweets.jpg",
        name: "Sweets",
        category: "Evening",
        price: "50Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    },
    {
        id: 13,
        image: "images/veg-thali.jpg",
        name: "Veg Thali",
        category: "Dinner",
        price: "80Rs",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo eveniet blanditiis maxime facilis consectetur perspiciatis maxime facilis consectetur perspiciatis?",
    }
];

export default Menu;